name: build
on:
  push:
    branches:
      - main
      - release
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Install Docker image dependencies
        working-directory: ./images/main
        run: npm i
      - name: Build Docker image
        working-directory: ./images/main
        run: docker build . -t mocks-server:main
      - name: Run tests
        run: npm run test
