name: build
on:
  push:
    branches:
      - master
      - release
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./main
        run: npm i
      - name: Build Docker image
        working-directory: ./main
        run: docker build . -t mocks-server:main
